on:
  push:
#    branches: [ "*" ]
  pull_request:
#    branches: [ "*" ]
name: "Java CI with Gradle"
permissions:
  contents: write
  issues: read
  checks: write
  statuses: read
  pull-requests: write 

jobs:
  build:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4  
 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
 
    - name: Build with Gradle
      run: ./gradlew build
 
    - name: Test with Gradle
      run: ./gradlew test
 
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/
 
    - name: Upload test coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/reports/jacoco/


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      